package com.myspace.vibrations;

no-loop

rule 'Machine-One-Class-B-Check'
    salience 2
    when
        $part: Part(
            machine_id == "1" && 
            ((
                (vibration_level_1 < 41 &&
                vibration_level_1 > -41) 
                &&
                (vibration_level_2 < 41 &&
                vibration_level_2 > -41)
                &&
                (vibration_level_3 > 201 ||
                vibration_level_3 < -201)
            )
            ||
            (
                (vibration_level_1 > 41 ||
                vibration_level_1 < -41)
                &&
                (vibration_level_2 < 41 &&
                vibration_level_2 > -41) 
                &&
                (vibration_level_3 < 201 &&
                vibration_level_3 > -201) 
            ) ||
            (
                (vibration_level_2 > 41 ||
                vibration_level_2 < -41) 
                &&
                (vibration_level_3 < 201 &&
                vibration_level_3 > -201)
                &&
                (vibration_level_1 < 41 &&
                vibration_level_1 > -41)
            ))
        )
    then
        modify($part) {
            setQuality_class("B")
        }
end