version: "3.8"
services:
  iiotsimulator:
    build: .
    container_name: ${CONNAME}
    volumes:
      - ./configs/config.json:/app/configs/config.json
      - ./configs/logging.yml/:/app/configs/logging.yml
    network_mode:
        host