version: "3.8"
services:
  aggregator:
    build: .
    container_name: ${CONNAME}
    environment:
        path_name: "${PATHNAME}"
    network_mode:
      host
    volumes:
      - ./logs/:/app/logs/
      - ./config/:/app/config/
      - ./../../component_base_class/component_base_class.py:/app/component_base_class/component_base_class.py
