version: 1

formatters:
  simple:
    format: "%(asctime)s %(name)s %(levelname)s - %(message)s"
  extended:
    format: "%(asctime)s %(name)s %(levelname)s %(filename)s:%(lineno)d - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: extended

root:
  handlers: [console]
  level: DEBUG
