---
version: "3.8"
services:    
    simulator:
        build: ./../producers/iiot-simulator/.
        volumes:
            - ./../producers/iiot-simulator/configs/config_democase_2.json:/app/configs/config.json
            - ./../producers/iiot-simulator/configs/logging_democase_2.yml/:/app/configs/logging.yml
    influx_consumer:
        build: ./../consumers/influx/.
        network_mode:
          host
        volumes:
          - ./../consumers/influx/logs/demo_case_2_logs/:/influx/logs/
          - ./../consumers/influx/config/config_demo_case_2.json:/influx/config/config.json
    aggregator:
        build: ./../streams/aggregator/.
        volumes:
            - ./configs/config_demo_case_2.json:/app/configs/config.json
            - ./configs/logging_demo_case_2.yml/:/app/configs/logging.yml
    influx_consumer_2:
        build: ./../consumers/influx/.
        network_mode:
          host
        volumes:
          - ./../consumers/influx/logs/demo_case_1_logs_2/:/influx/logs/
          - ./../consumers/influx/config/config_demo_case_1_influxconsumer_2.json:/influx/config/config.json
    anonymizer:
        build: ./../streams/anoymizer/.
        volumes:
            - ./configs/config_demo_case_2.json:/app/configs/config.json
            - ./configs/logging_demo_case_2.yml/:/app/configs/logging.yml
    webhook_consumer:
        build: ./../consumers/influx/.
        volumes:
          - ./../consumers/webhook/logs/demo_case_2_logs/:/webhook/logs/
          - ./../consumers/webhook/config/config_demo_case_2.json:/webhook/config/config.json
