---
version: "3.8"
services:    
    simulator:
        build: ./../producers/iiot-simulator/.
        volumes:
            - ./../producers/iiot-simulator/configs/config_democase_1.json:/app/configs/config.json
            - ./../producers/iiot-simulator/configs/logging_democase_1.yml/:/app/configs/logging.yml
    influx_consumer:
        build: ./../consumers/influx/.
        network_mode:
          host
        volumes:
          - ./../consumers/influx/logs/demo_case_1_logs/:/influx/logs/
          - ./../consumers/influx/config/config_demo_case_1.json:/influx/config/config.json
    payperx:
        build: ./../streams/payperx/.
        network_mode:
            host
        volumes:
            - ./../streams/payperx/config/config_democase_1.json:/app/config/config.json
    influx_consumer_2:
        build: ./../consumers/influx/.
        network_mode:
          host
        volumes:
          - ./../consumers/influx/logs/demo_case_1_logs_2/:/influx/logs/
          - ./../consumers/influx/config/config_demo_case_1_influxconsumer_2.json:/influx/config/config.json